### ISSUE TITLE
mod_assign: Atualizar o estilo no tema para melhor UX

### ISSUE THREAD

**Issue by BrenoAugustoUEMS** [BrenoAugustoUEMS/almondb-editais#3]
```CSS
/* Aplica apenas dentro do Advanced Grading */
#rubric-advancedgrading .criterion {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
}

/* Ajusta as células internas para que ocupem toda a largura */
#rubric-advancedgrading .criterion > td {
    display: flex;
    flex-direction: row;
}

/* Ajuste para os níveis dentro da rubrica */
#rubric-advancedgrading .levels {
    display: flex;
    flex-direction: row;
    width: 100%
}

/* Ajuste para o campo de comentário */
#rubric-advancedgrading .remark textarea {
    display: none;
}
```
